=== shraga89/Ontobuilder-Research-Environment/ORE_src/dtds/ontology.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by pepito (personal) -->
<!ELEMENT ontology (classes*, terms)>
<!ATTLIST ontology
	name CDATA #REQUIRED
	title CDATA #REQUIRED
	site CDATA #IMPLIED
        type (full | light) "full"
>
<!ELEMENT classes (class*)>
<!ELEMENT terms (term*)>
<!ELEMENT class (domain, attributes, axioms, subclasses)>
<!ATTLIST class
	name CDATA #REQUIRED
>
<!ELEMENT attributes (attribute*)>
<!ELEMENT axioms (axiom*)>
<!ELEMENT subclasses (class*)>
<!ELEMENT domain (entry | term)*>
<!ATTLIST domain
	name CDATA #IMPLIED
	type CDATA #IMPLIED
>
<!ELEMENT entry ANY>
<!ELEMENT attribute (domain)>
<!ATTLIST attribute
	name CDATA #REQUIRED
	value CDATA #IMPLIED
>
<!ELEMENT axiom (#PCDATA)>
<!ATTLIST axiom
	name CDATA #REQUIRED
>
<!ELEMENT term (domain, attributes, axioms, relationships, subterms)>
<!ATTLIST term
	id CDATA #IMPLIED
	name CDATA #REQUIRED
	value CDATA #IMPLIED
	class CDATA #IMPLIED
>
<!ELEMENT relationships (relationship*)>
<!ELEMENT subterms (term*)>
<!ELEMENT relationship (source, targets)>
<!ATTLIST relationship
	name CDATA #REQUIRED
>
<!ELEMENT source (#PCDATA)>
<!ELEMENT targets (#PCDATA)>

=== shraga89/Ontobuilder-Research-Environment/schema/MevoJerusalem.xml_NeptuneEilat.xml_EXACT/MevoJerusalem.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ontology SYSTEM "dtds/ontology.dtd">
<ontology name="Mevo_Jerusalem" title="Mevo Jerusalem Tower - Residential Hotel - Secure Reservation" type="full" site="file:/C:/Documents and Settings/Eyal_ami/Desktop/Mevo Jerusalem Tower - Residential Hotel - Secure Reservation.htm">
    <classes>
        <class name="page">
            <domain type="" />
            <attributes />
            <axioms />
            <subclasses />
        </class>
        <class name="form">
            <domain type="" />
            <attributes>
                <attribute name="method" value="get">
                    <domain name="Choice" type="choice">
                        <entry>post</entry>
                        <entry>get</entry>
                    </domain>
                </attribute>
                <attribute name="action">
                    <domain name="URL" type="url" />
                </attribute>
            </attributes>
            <axioms />
            <subclasses />
        </class>
        <class name="input">
            <domain type="" />
            <attributes>
                <attribute name="name">
                    <domain name="Text" type="text" />
                </attribute>
                <attribute name="disabled" value="false">
                    <domain name="Boolean" type="boolean" />
                </attribute>
            </attributes>
            <axioms />
            <subclasses>
                <class name="text">
                    <domain type="" />
                    <attributes>
                        <attribute name="name">
                            <domain name="Text" type="text" />
                        </attribute>
                        <attribute name="disabled">
                            <domain name="Boolean" type="boolean" />
                        </attribute>
                        <attribute name="type" value="text">
                            <domain type="" />
                        </attribute>
                        <attribute name="defaultValue">
                            <domain name="Text" type="text" />
                        </attribute>
                        <attribute name="value">
                            <domain name="Text" type="text" />
                        </attribute>
                        <attribute name="size">
                            <domain name="Positive Integer" type="pinteger" />
                        </attribute>
                        <attribute name="maxLength">
                            <domain name="Positive Integer" type="pinteger" />
                        </attribute>
                        <attribute name="readOnly" value="false">
                            <domain name="Boolean" type="boolean" />
                        </attribute>
                    </attributes>
                    <axioms />
                    <subclasses />
                </class>
                <class name="password">
                    <domain type="" />
                    <attributes>
                        <attribute name="name">
                            <domain name="Text" type="text" />
                        </attribute>
                        <attribute name="disabled">
                            <domain name="Boolean" type="boolean" />
                        </attribute>
                        <attribute name="type" value="password">
                            <domain type="" />
                        </attribute>
                        <attribute name="defaultValue">
                            <domain name="Text" type="text" />
                        </attribute>
                        <attribute name="size">
                            <domain name="Positive Integer" type="text" />
                        </attribute>
                        <attribute name="maxLength">
                            <domain name="Positive Integer" type="pinteger" />
                        </attribute>
                        <attribute name="readOnly" value="false">
                            <domain name="Boolean" type="boolean" />
                        </attribute>
                    </attributes>
                    <axioms />
                    <subclasses />
                </class>
                <class name="file">
                    <domain type="" />
                    <attributes>
                        <attribute name="name">
                            <domain name="Text" type="text" />
                        </attribute>
                        <attribute name="disabled">
                            <domain name="Boolean" type="boolean" />
                        </attribute>
                        <attribute name="type" value="file">
                            <domain type="" />
                        </attribute>
                        <attribute name="size">
                            <domain name="Positive Integer" type="pinteger" />
                        </attribute>
                        <attribute name="maxLength">
                            <domain name="Positive Integer" type="pinteger" />
                        </attribute>
                        <attribute name="readOnly" value="false">
                            <domain name="Boolean" type="boolean" />
                        </attribute>
                    </attributes>
                    <axioms />
                    <subclasses />
                </class>
                <class name="hidden">
                    <domain type="" />
                    <attributes>
                        <attribute name="name">
                            <domain name="Text" type="text" />
                        </attribute>
                        <attribute name="disabled">
                            <domain name="Boolean" type="boolean" />
                        </attribute>
                        <attribute name="type" value="hidden">
                            <domain type="" />
                        </attribute>
                        <attribute name="type" value="button">
                            <domain type="" />
                        </attribute>
                    </attributes>
                    <axioms />
                    <subclasses />
                </class>
                <class name="checkbox">
                    <domain type="" />
                    <attributes>
                        <attribute name="name">
                            <domain name="Text" type="text" />
                        </attribute>
                        <attribute name="disabled">
                            <domain name="Boolean" type="boolean" />
                        </attribute>
                        <attribute name="type" value="checkbox">
                            <domain type="" />
                        </attribute>
                    </attributes>
                    <axioms />
                    <subclasses />
                </class>
                <class name="radio">
                    <domain type="" />
                    <attributes>
                        <attribute name="name">
                            <domain name="Text" type="text" />
                        </attribute>
                        <attribute name="disabled">
                            <domain name="Boolean" type="boolean" />
                        </attribute>
                        <attribute name="type" value="radio">
                            <domain type="" />
                        </attribute>
                    </attributes>
                    <axioms />
                    <subclasses />
                </class>
                <class name="select">
                    <domain type="" />
                    <attributes>
                        <attribute name="name">
                            <domain name="Text" type="text" />
                        </attribute>
                        <attribute name="disabled">
                            <domain name="Boolean" type="boolean" />
                        </attribute>
                        <attribute name="type" value="select">
                            <domain type="" />
                        </attribute>
                        <attribute name="size">
                            <domain name="Positive Integer" type="pinteger" />
                        </attribute>
                        <attribute name="multiple" value="false">
                            <domain name="Boolean" type="boolean" />
                        </attribute>
                    </attributes>
                    <axioms />
                    <subclasses />
                </class>
                <class name="textarea">
                    <domain type="" />
                    <attributes>
                        <attribute name="name">
                            <domain name="Text" type="text" />
                        </attribute>
                        <attribute name="disabled">
                            <domain name="Boolean" type="boolean" />
                        </attribute>
                        <attribute name="type" value="textarea">
                            <domain type="" />
                        </attribute>
                        <attribute name="defaultValue">
                            <domain name="Text" type="text" />
                        </attribute>
                        <attribute name="rows">
                            <domain name="Positive Integer" type="pinteger" />
                        </attribute>
                        <attribute name="cols">
                            <domain name="Positive Integer" type="pinteger" />
